import Card from "@/components/Card";
import Navbar from "@/components/Navbar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>myapp bootstraps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <h2
        className="text-center "
        style={{ color: "#023e8a", marginTop: "80px" }}
      >
        My Galery
      </h2>
      <div className="d-flex flex-wrap gap-3 justify-content-center mb-5 px-3">
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
      </div>
    </>
  );
}
